### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by raghavzns** [BakingBrains/People_counting_basic#2]
`python3 counting_people.py --video test.mp4                                                                                                                            ─╯
`
[INFO] loading model...
Traceback (most recent call last):
  File "counting_people.py", line 223, in <module>
    outs = net.forward(getOutputsNames(net))
  File "counting_people.py", line 62, in getOutputsNames
    return [layersNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "counting_people.py", line 62, in <listcomp>
    return [layersNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

**Comment by BakingBrains** [comment]
change line 62 to [layersNames[i - 1] for i in net.getUnconnectedOutLayers()]
