### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by zeynepkoyun** [BakingBrains/People_counting_basic#3]
Hello @BakingBrains 

First of all, thank you for your code. I tried your code for testing, but I think you edited it after uploading to github.
I made the following changes for your code to work, but the detect operation was not successful. Can you check to see if there is an incorrect operation?

Arrangements:
1. In the "**counting_people.py**" file, I wrote the 7th and 8th lines as follows:
**_from utils.centroidtracker import CentroidTracker
from utils.trackableobject import TrackableObject_**

2. I wrote line 65 in the "**counting_people.py**" file as "_**return [layersNames[i-1] for i in net.getUnconnectedOutLayers()**_]".

3. I deleted line 101 **_"i=i[0]_**" in "**counting_people.py**" file.

**Comment by BakingBrains** [comment]
@zeynepkoyun please clone and run it again. I have modified it now.
Thank you
