### ISSUE TITLE
Fps is very slow

### ISSUE THREAD

**Issue by DeveshPundir** [BakingBrains/People_counting_basic#5]
Sir how to increase the speed of video while finding the result it is very slow.I changed the height and width to 288 to increase but still not working.

**Comment by BakingBrains** [comment]
@DeveshPundir Yeah, this is the basics for the counting of objects using detection and tracking algorithm. For better output visualization as well as inference speed, please look into ```DeepSORT or StrongSORT```. You can use YOLOv5 or v7 with ``DeepSORT or StrongSORT```

**Comment by DeveshPundir** [comment]
ok thank u sir
