### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by naqibsyahmi** [BakingBrains/People_counting_basic#6]
I tried running it but i encountered this error

from utils.centroidtracker import CentroidTracker
from utils.trackableobject import TrackableObject

For some reason, it cannot identify

ModuleNotFoundError: No module named 'utils.centroidtracker'

**Comment by BakingBrains** [comment]
@naqibsyahmi you need to clone the repo and run [counting_people.py](https://github.com/BakingBrains/People_counting_basic/blob/main/counting_people.py) in the same directory.

The centroidtracker file is inside utils folder

**Comment by naqibsyahmi** [comment]
Okay got it thanks

Another question, how would I implement the same program but using YOLOv5?

**Comment by BakingBrains** [comment]
@naqibsyahmi you can use YOLOv5 with deepSORT or StrongSORT to track the person and get the count. 
check this out: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet
